language: php

sudo: false

git:
  depth: 3

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-source"

php:
  - 5.5
  - 5.6
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable --prefer-source"
    - php: 7.0
      env:
        - TEST_VERSION=true
        - COMPOSER_FLAGS="--prefer-stable --prefer-source"
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - if [[ $TEST_VERSION != true && -f "/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini" ]]; then phpenv config-rm xdebug.ini; fi
  - composer global require hirak/prestissimo
  - composer self-update --stable --no-progress

install:
  - travis_retry composer update $COMPOSER_FLAGS --no-interaction --no-scripts --no-progress
  - if [[ $TEST_VERSION == true ]]; then travis_retry composer require satooshi/php-coveralls:dev-master $COMPOSER_FLAGS --no-interaction --no-scripts --no-progress ; fi

script:
  - if [[ $TEST_VERSION == true ]]; then composer qa & composer phpunit-clover ; fi
  - if [[ $TEST_VERSION != true ]]; then composer phpunit ; fi

after_script:
  - if [[ $TEST_VERSION == true ]]; then travis_retry php vendor/bin/coveralls --verbose ; fi
